# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='product.Restaurant'),
        ),
    ]
