# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_cart_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
