# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180829_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
